### ISSUE TITLE
Missing profile?

### ISSUE THREAD

**Issue by yonas** [alibama/cvillecouncilus#2]
Where is your custom Drupal profile located?

**Comment by alibama** [comment]
hi yonas - not sure man - could you send me a link on how to do a better job of this?  really glad to work on it - this is my first go at releasing a drupal distro :)

**Comment by yonas** [comment]
I would start with https://www.drupal.org/node/1022020 and use other distros as an example.

**Comment by alibama** [comment]
cool - I used https://www.drupal.org/project/profiler_builder and have added the profile in to the site profiles - thanks for the comment & advice
